language: node_js
node_js:
   - "7"
branches:
   only:
      - master
before_script:
   - npm install --save-dev gh-pages
script:
   - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master